void AlexAfficher();
void AlexAMORCER();
int bAlexAnalyser(char *sCode);
char *sAlexChaine(int nLexeme);
int bAlexDate(int uLexeme);
void AlexDenoncer(int nLexeme);
int bAlexEntier(int uLexeme);
int nAlexEntier(int uLexeme);
int nAlexExpression(int uLexeme);
int bAlexFinFichier(int uLexeme);
int bAlexHoraire(int uLexeme);
int bAlexIdentificateur(int uLexeme);
void AlexINITIALISER();
int nAlexInstruction(int uLexeme);
int bAlexLexeme(int uLexeme);
int nAlexLigne(int uLexeme);
int bAlexOperateur(int uLexeme,char cOperateur);
int bAlexParenthese(int uLexeme, char cParenthese);
int nAlexProgramme(int uLexeme);
int bAlexReel(int uLexeme);
float fAlexReel(int uLexeme);
int bAlexSeparateur(int uLexeme);
int nAlexSuite(int uLexeme);
void AlexTESTER(int iTest);
int bAlexTexte(int uLexeme);
